### PR TITLE
ST-009

### LINKED ISSUE #20: ST-009 russian language support
**Description**
As a Russian speaking user, I want to have support for Russian, so that I can use the app

**Acceptance criteria**
* Selector between English and Russian in the setting view
* All texts are in the selected language
* default is English

**Additional context**
* highest priority in the next sprint

### PR DESCRIPTION
**Pull request by katasc22**

### CODE REVIEW

**Comment by Chr16t0p** [comment]
very good idea to not reset to settings screen! well done!

**Review by kereczt — APPROVED** [review]
Отличная работа

**Comment by Chr16t0p** [comment]
👍🏼

**Review by phil3pi — APPROVED** [review]
nice language integration
@katasc22 
@Chr16t0p 
@chairwinker

**Pull request merged**
